import { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'
import FishTank from '../components/fish-tank'
import { FishContextProvider } from '../contexts/fishes'
import { Colors } from '../styles/colors'

const Container = styled.div`
  height: 100vh;
  width: 100vw;
  background: linear-gradient(
    ${Colors.lightBackground},
    ${Colors.darkBackground}
  );
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
`

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>My aquarium</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Fish tank</h1>
      <h2>of the century</h2>
      <FishContextProvider>
        <FishTank />
      </FishContextProvider>
    </Container>
  )
}

export default Home
